export const LONDON_BOROUGHS = [
  "Barking and Dagenham",
  "Barnet",
  "Bexley",
  "Brent",
  "Bromley",
  "Camden",
  "Croydon",
  "Ealing",
  "Enfield",
  "Greenwich",
  "Hackney",
  "Hammersmith and Fulham",
  "Haringey",
  "Harrow",
  "Havering",
  "Hillingdon",
  "Hounslow",
  "Islington",
  "Kensington and Chelsea",
  "Kingston upon Thames",
  "Lambeth",
  "Lewisham",
  "Merton",
  "Newham",
  "Redbridge",
  "Richmond",
  "Southwark",
  "Sutton",
  "Tower Hamlets",
  "Waltham Forest",
  "Wandsworth",
  "Westminster",
] as const;

export const ACTIVITY_TYPES = [
  "Soft Play",
  "Bowling",
  "Trampoline Park",
  "Swimming Pool",
  "Art & Craft",
  "Cooking Class",
  "Magic Show",
  "Dance/Music",
  "Animal Experience",
  "Bouncy Castle",
  "Cinema",
  "Laser Tag",
  "Go Karting",
  "Mini Golf",
  "Climbing Wall",
  "Science Workshop",
  "STEM Activity",
  "Drama Workshop",
  "Face Painting",
  "Balloon Artist",
  "Puppet Show",
  "Karaoke",
  "Video Game Arcade",
  "Escape Room",
  "Sports",
  "Outdoor",
  "Museum",
  "Ice Skating",
  "Martial Arts",
  "Indoor Skiing",
  "Nature Walk",
  "Storytelling",
  "Film",
  "Zoo",
  "Water Sports",
] as const;

export const AGE_RANGES = [
  { label: "0-3 years", value: "0-3", min: 0, max: 3 },
  { label: "4-6 years", value: "4-6", min: 4, max: 6 },
  { label: "7-9 years", value: "7-9", min: 7, max: 9 },
  { label: "10-12 years", value: "10-12", min: 10, max: 12 },
  { label: "13-16 years", value: "13-16", min: 13, max: 16 },
] as const;

export const PARTY_SIZES = [
  { label: "1-10 children", value: "1-10", min: 1, max: 10 },
  { label: "11-20 children", value: "11-20", min: 11, max: 20 },
  { label: "21-30 children", value: "21-30", min: 21, max: 30 },
  { label: "31-50 children", value: "31-50", min: 31, max: 50 },
  { label: "50+ children", value: "50+", min: 50, max: 100 },
] as const;

export const ACTIVITY_GROUPS = [
  {
    label: "🏠 Indoor",
    value: "indoor",
    activities: [
      "Soft Play",
      "Bowling",
      "Trampoline Park",
      "Swimming Pool",
      "Cinema",
      "Laser Tag",
      "Go Karting",
      "Mini Golf",
      "Climbing Wall",
      "Video Game Arcade",
      "Escape Room",
      "Ice Skating",
      "Indoor Skiing",
    ],
  },
  {
    label: "🌳 Outdoor",
    value: "outdoor",
    activities: [
      "Animal Experience",
      "Nature Walk",
      "Zoo",
      "Water Sports",
      "Sports",
      "Outdoor",
    ],
  },
  {
    label: "🎨 Creative",
    value: "creative",
    activities: [
      "Art & Craft",
      "Cooking Class",
      "Science Workshop",
      "STEM Activity",
      "Drama Workshop",
      "Face Painting",
      "Balloon Artist",
      "Puppet Show",
    ],
  },
  {
    label: "🎭 Entertainment",
    value: "entertainment",
    activities: [
      "Magic Show",
      "Dance/Music",
      "Bouncy Castle",
      "Karaoke",
      "Storytelling",
      "Film",
    ],
  },
  {
    label: "⚡ Active",
    value: "active",
    activities: [
      "Sports",
      "Climbing Wall",
      "Trampoline Park",
      "Martial Arts",
      "Swimming Pool",
      "Go Karting",
    ],
  },
] as const;

export type Borough = (typeof LONDON_BOROUGHS)[number];
export type ActivityType = (typeof ACTIVITY_TYPES)[number];
